### Importar biblioteca numpy:

In [1]:
import numpy as np

# Arrays (matrizes)

### 1 dimensão:

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

### 2 dimensões:

In [5]:
minha_matriz = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

In [6]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Obs.: A quantidade de dimensões é definida pela quantidade de colchetes abertos na lista

## Métodos

### Arange

Criação de arrays com muitos termos.

In [7]:
np.arange(0 , 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

quando colocado o step, define uma terceira condição:

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### Zeros e Uns

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Identidade

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Linspace

É como o arange, mas o terceiro parametro mostra a quantidade de numero que deve ser mostrado:

In [16]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0, 100, 9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

### Aleatóriedade (Random)

### Rand

aleatoriedade com intervalos tirados de uma distribuição uniforme

#### 1 dim

In [26]:
np.random.rand(5)

array([0.04219   , 0.2901627 , 0.20795579, 0.74580612, 0.28613917])

In [21]:
np.random.rand(5) * 100

array([55.15439727, 25.21906406, 98.86701689,  7.2606692 , 13.45082525])

#### 2 dim

In [22]:
np.random.rand(5, 4)

array([[9.69544374e-01, 4.80593035e-01, 6.18762144e-01, 1.28705887e-01],
       [8.88270647e-01, 8.10889104e-01, 6.27362508e-01, 5.64836427e-01],
       [9.68358511e-01, 3.07174682e-01, 6.11950782e-01, 7.75413351e-01],
       [3.61528039e-04, 3.69457798e-01, 3.17430665e-01, 5.39434153e-01],
       [6.07311751e-01, 1.06248353e-02, 6.05977388e-01, 5.81575199e-01]])

#### 3 dim

In [23]:
np.random.rand(5, 4, 3)

array([[[0.85480782, 0.17561609, 0.10653552],
        [0.76667667, 0.46357223, 0.85788023],
        [0.58270349, 0.38464264, 0.0996509 ],
        [0.08220163, 0.53030585, 0.73303585]],

       [[0.92319125, 0.10681126, 0.19604453],
        [0.77871388, 0.70371145, 0.37484312],
        [0.18111755, 0.45131679, 0.8555322 ],
        [0.02641902, 0.69712781, 0.72415336]],

       [[0.2095474 , 0.90204527, 0.70765306],
        [0.6550468 , 0.45994325, 0.91639738],
        [0.74187087, 0.08487062, 0.92360257],
        [0.05369256, 0.35721365, 0.31409595]],

       [[0.61068624, 0.46355224, 0.56824945],
        [0.88967103, 0.78586175, 0.98964044],
        [0.75243693, 0.78039638, 0.30337925],
        [0.99976364, 0.98658342, 0.40088732]],

       [[0.60203606, 0.44854263, 0.65352852],
        [0.96578804, 0.20524017, 0.63942766],
        [0.00494147, 0.87194943, 0.14101889],
        [0.07869831, 0.61494463, 0.72948599]]])

imagine um cubo onde 5 é a profundidade, 4 a altura e 3 a largura

### Randn

aleatoriedade tirada de uma distribuição normal

In [25]:
np.random.randn(5)

array([-0.51878916, -1.64593475, -0.9729449 ,  0.77734478,  0.21423358])

### Randint

In [27]:
np.random.randint(0, 100, 10)

array([69,  8, 23, 11, 18, 77, 55, 91, 60, 37])

### Reshape

In [28]:
arr = np.random.rand(25)

In [29]:
arr

array([0.67813316, 0.52669408, 0.07224377, 0.72057657, 0.79561147,
       0.4233974 , 0.39044049, 0.84375749, 0.95574179, 0.04362614,
       0.62256953, 0.11318782, 0.43093394, 0.49994092, 0.96976617,
       0.9703014 , 0.62398609, 0.51310491, 0.10447153, 0.03340341,
       0.68516909, 0.17415342, 0.54243023, 0.05167392, 0.46051807])

In [32]:
arr = arr.reshape((5, 5))

In [33]:
arr

array([[0.67813316, 0.52669408, 0.07224377, 0.72057657, 0.79561147],
       [0.4233974 , 0.39044049, 0.84375749, 0.95574179, 0.04362614],
       [0.62256953, 0.11318782, 0.43093394, 0.49994092, 0.96976617],
       [0.9703014 , 0.62398609, 0.51310491, 0.10447153, 0.03340341],
       [0.68516909, 0.17415342, 0.54243023, 0.05167392, 0.46051807]])

Deixou de ser um vetor com 25 elementos e se transformou em uma matriz 5x5

### Max, Min, Argmax, Argmin

In [34]:
arr.max()

0.9703013954305726

In [35]:
arr.min()

0.03340340677171316

In [36]:
arr.argmax()

15

Argmax é o indice onde o maior argumento se encontra

In [37]:
arr.argmin()

19

# Indexação e fatiamento de arrays

In [40]:
arr = np.arange(0, 30, 3)

In [41]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Buscar elemento pela posição:

In [42]:
arr[3]

9

Buscar multiplos elementos:

In [43]:
arr[2:5]

array([ 6,  9, 12])

In [44]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [45]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

Alterar os elemntos a partir da busca:

In [46]:
arr[2:] = 100

In [47]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

#### Bidimensionais

In [66]:
arr = np.arange(50).reshape((5, 10))

In [49]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Ver o tamanho do array:

In [50]:
arr.shape

(5, 10)

### Retirar Slices:

#### método com 2 colchetes:

primeiro colchete é as linhas e o segundo as colunas

In [51]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [52]:
arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [75]:
arr2 = arr[:3]

In [60]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Modificando os dados

In [76]:
arr2[:] = 100

In [65]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [67]:
arr3 = arr[:3].copy()

In [68]:
arr3[:] = 100

In [69]:
arr3

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [70]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

#### Com o metódo copy a alteração é feita apenas no slice e não em toda a matriz

Método com virgulas:

In [78]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [80]:
arr > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [81]:
bol = arr > 50

In [82]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

# Operações com NumPy

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 16)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [7]:
arr / arr

<ipython-input-7-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [8]:
1 / arr

<ipython-input-8-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [9]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225], dtype=int32)

In [10]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [11]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

### Funções:

In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [15]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [16]:
np.mean(arr)

7.5

In [17]:
np.std(arr)

4.6097722286464435

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [19]:
np.max(arr)

15

In [21]:
arr.max()

15

In [22]:
arr.min()

0

## Link para todas as funções NumPy:

https://docs.scipy.org/doc/numpy/reference/ufuncs.html